version: '3'
services:
  postgres:
    image: postgres:15
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER = ${POSTGRES_USER}
      - POSTGRES_PASSWORD = ${POSTGRES_PASSWORD}
      - POSTGRES_DB = ${POSTGRES_DB}
  redis:
    image: redis:7.0
    ports:
      - 6379:6379
    volumes:
      - "./data/redis:/data"
  app:
    build: 
      context: ./
      dockerfile: ./build/package/app/Dockerfile
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
volumes:
  db-store: